# Generated by Django 4.2.30 on 2026-08-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="お名前")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="メールアドレス"),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="電話番号"
                    ),
                ),
                ("message", models.TextField(verbose_name="メッセージ")),
                ("is_read", models.BooleanField(default=False, verbose_name="既読")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                (
                    "related_work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to="works.work",
                        verbose_name="関連する作品",
                    ),
                ),
            ],
            options={
                "verbose_name": "お問い合わせ",
                "verbose_name_plural": "お問い合わせ",
                "ordering": ["-created_at"],
            },
        ),
    ]
