# Generated by Django 4.2.30 on 2026-08-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="キャプション"
                    ),
                ),
                (
                    "image_pc",
                    models.ImageField(
                        upload_to="core/hero/pc/", verbose_name="PC用画像"
                    ),
                ),
                (
                    "image_sp",
                    models.ImageField(
                        blank=True,
                        upload_to="core/hero/sp/",
                        verbose_name="スマートフォン用画像",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開する"),
                ),
            ],
            options={
                "verbose_name": "ヒーロースライド",
                "verbose_name_plural": "ヒーロースライド",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="表示名"),
                ),
                (
                    "role_title",
                    models.CharField(
                        blank=True,
                        help_text="例: multi creator",
                        max_length=100,
                        verbose_name="肩書き",
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(blank=True, max_length=100, verbose_name="出身地"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="誕生日"),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=200, verbose_name="学校"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="自己紹介")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        upload_to="core/profile/",
                        verbose_name="プロフィール画像",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "サイトプロフィール",
                "verbose_name_plural": "サイトプロフィール",
            },
        ),
        migrations.CreateModel(
            name="SnsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("twitter", "X (Twitter)"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sns_links",
                        to="core.siteprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNSリンク",
                "verbose_name_plural": "SNSリンク",
                "ordering": ["display_order"],
            },
        ),
    ]
