# Generated by Django 4.2.30 on 2026-08-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ジャンル名"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="スラッグ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        upload_to="works/genres/bg/",
                        verbose_name="背景画像",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開する"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ジャンル",
                "verbose_name_plural": "ジャンル",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="タグ名"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, unique=True, verbose_name="スラッグ"
                    ),
                ),
            ],
            options={
                "verbose_name": "タグ",
                "verbose_name_plural": "タグ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="作品名")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="スラッグ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="作品解説")),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="1行1項目で入力してください。",
                        verbose_name="見どころ",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(blank=True, null=True, verbose_name="制作日"),
                ),
                (
                    "production_hours",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="制作時間（時間）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("published", "公開")],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="おすすめ表示"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="閲覧数"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="公開日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="works",
                        to="works.genre",
                        verbose_name="ジャンル",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="works.tag", verbose_name="タグ"
                    ),
                ),
            ],
            options={
                "verbose_name": "作品",
                "verbose_name_plural": "作品",
                "ordering": ["display_order", "-published_at", "-created_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ツール名"
                    ),
                ),
            ],
            options={
                "verbose_name": "使用ツール",
                "verbose_name_plural": "使用ツール",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "画像"),
                            ("video", "動画"),
                            ("audio", "音声"),
                            ("embed", "外部埋め込み(YouTube等)"),
                            ("document", "ドキュメント(PDF等)"),
                        ],
                        max_length=20,
                        verbose_name="メディア種別",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="works/media/%Y/%m/",
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube/SoundCloud等の埋め込みURL。外部埋め込みの場合はこちらを使用。",
                        verbose_name="外部URL",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="キャプション"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="一覧表示のサムネイルとして使用します。",
                        verbose_name="サムネイルにする",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="works.work",
                        verbose_name="作品",
                    ),
                ),
            ],
            options={
                "verbose_name": "作品メディア",
                "verbose_name_plural": "作品メディア",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="work",
            name="tools",
            field=models.ManyToManyField(
                blank=True, to="works.worktool", verbose_name="使用ツール"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["status", "published_at"], name="works_work_status_f8643b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["genre", "status"], name="works_work_genre_i_644b8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["title"], name="works_work_title_64b566_idx"),
        ),
    ]
